

language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $ACCESSKEY
#   secret_access_key: $SECRETKEY
#   region: "us-west-2"
#   app: "django-tutorial"
#   env: "django-env"
#   bucket_name: "elasticbeanstalk-us-west-2-978364673633"
