

language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m black . --check
  - flake8 .
  - coverage run --source=jgswe,polls manage.py test

after_script:
  - python -m coveralls

# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $ACCESSKEY
#   secret_access_key: $SECRETKEY
#   region: "us-west-2"
#   app: "django-tutorial"
#   env: "django-env"
#   bucket_name: "elasticbeanstalk-us-west-2-978364673633"
